version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build:
      context: backend/
      dockerfile: Dockerfile.dev # Use the development Dockerfile
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://host.docker.internal:27017/blog
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app # Bind mount for live code changes
      - /app/node_modules # Prevent overwriting node_modules
    command: ['npx', 'nodemon', 'index.js'] # Optional: Override CMD if needed
  blog-frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev # Specify the development Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:3001/api/v1
        VITE_PORT: 3000
    ports:
      - '3000:3000' # Expose the Vite development server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app:delegated # Bind mount for live code changes
      - /app/node_modules # Prevent overwriting node_modules
