FROM node:23
WORKDIR /app

# Copy only package files to install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the port used by the backend server
EXPOSE 3001

# Install nodemon for live reloading
RUN npm install --save-dev nodemon

# Run the backend server with nodemon for live reloading
CMD ["npx", "nodemon", "index.js"]