name: Blog Backend CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Print current working directory
        run: pwd
      - name: Install dependencies
        run: npm install
      - name: Print current working directory
        run: pwd
      - name: Check if eslint.config.js exists
        run: |
          if [ -f ./eslint.config.js ]; then
            echo "eslint.config.js exists."
          else
            echo "eslint.config.js is missing!" && exit 1
          fi
      - name: Run linter on backend
        run: npm run lint
      - name: Print current working directory
        run: pwd
      - name: Run backend tests
        run: npm test
